import '~/styles/globals.css'

import { type Metadata } from 'next'
import { TRPCReactProvider } from '~/server/trpc/react'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'

const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${inter.className}`}>
            <body>
                Impact-Site-Verification: d0416977-8669-4d9e-9ffa-a14c5c8129db
                <ClerkProvider>
                    <TRPCReactProvider>{children}</TRPCReactProvider>
                </ClerkProvider>
            </body>
        </html>
    )
}
