import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '~/server/trpc/react'
import { ClerkProvider } from '@clerk/nextjs'
import Script from 'next/script'

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${GeistSans.variable}`}>
            <Script
                strategy="beforeInteractive"
                src="https://tpembar.com/Mzk4ODM4.js?t=398838"
            />
            <body>
                <ClerkProvider>
                    <TRPCReactProvider>{children}</TRPCReactProvider>
                </ClerkProvider>
            </body>
        </html>
    )
}
